name = "OpenTelemetryExporterOtlpProtoGrpc"
uuid = "83e8ae56-efb3-499e-9158-b649d4f902fc"
authors = ["Jun Tian <tianjun.cpp@gmail.com>"]
version = "0.0.1"

[deps]
OpenTelemetryAPI = "4f63ef3d-5940-44e7-a611-2d97696cffc9"
OpenTelemetryProto = "cc651e92-2989-4f95-bcc3-32e6fb6ac025"
OpenTelemetrySDK = "f5929ecf-be04-446c-b2f2-494e1fe70ee4"
gRPCClient = "aaca4a50-36af-4a1d-b878-4c443f2061ad"

[compat]
julia = "1"
OpenTelemetryAPI = "0.0.3"
OpenTelemetrySDK = "0.0.2"
OpenTelemetryProto = "0.0.1"
gRPCClient = "0.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
