name = "OpenTelemetry"
uuid = "c1912aec-9d41-432b-84fe-e17fd97255be"
authors = ["Jun Tian <tianjun.cpp@gmail.com> and contributors"]
version = "0.4.0"

[deps]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
OpenTelemetryAPI = "4f63ef3d-5940-44e7-a611-2d97696cffc9"
OpenTelemetryExporterOtlpProtoHttp = "f175482f-0544-4037-b362-361efbf21c04"
OpenTelemetryExporterPrometheus = "34e26579-e93c-4b5e-ba07-7afb633408c2"
OpenTelemetryProto = "cc651e92-2989-4f95-bcc3-32e6fb6ac025"
OpenTelemetrySDK = "f5929ecf-be04-446c-b2f2-494e1fe70ee4"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
OpenTelemetryAPI = "0.5"
OpenTelemetryExporterOtlpProtoHttp = "0.1.1"
OpenTelemetryExporterPrometheus = "0.3"
OpenTelemetryProto = "0.20"
OpenTelemetrySDK = "0.4"
Reexport = "1"
julia = "1"

[extras]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Term = "22787eb5-b846-44ae-b979-8e399b8463ab"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Logging", "Term", "Downloads", "HTTP"]
