name = "OpenTelemetryInstrumentationDownloads"
uuid = "0e26c271-1f4f-4c29-8c08-075e43f1441d"
authors = ["Jun Tian <tianjun.cpp@gmail.com>"]
version = "0.1.0"

[deps]
ArgTools = "0dad84c5-d112-42e6-8d28-ef12dabb789f"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
OpenTelemetryAPI = "4f63ef3d-5940-44e7-a611-2d97696cffc9"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
