name = "OpenTelemetrySDK"
uuid = "f5929ecf-be04-446c-b2f2-494e1fe70ee4"
authors = ["Jun Tian <tianjun.cpp@gmail.com>"]
version = "0.0.2"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
GarishPrint = "b0ab02a7-8576-43f7-aa76-eaa7c3897c54"
OpenTelemetryAPI = "4f63ef3d-5940-44e7-a611-2d97696cffc9"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1"
GarishPrint = "0.2"
OpenTelemetryAPI = "0.0.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
