name = "OpenTelemetrySDK"
uuid = "f5929ecf-be04-446c-b2f2-494e1fe70ee4"
authors = ["Jun Tian <tianjun.cpp@gmail.com>"]
version = "0.3.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
OpenTelemetryAPI = "4f63ef3d-5940-44e7-a611-2d97696cffc9"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
Term = "22787eb5-b846-44ae-b979-8e399b8463ab"

[compat]
Glob = "1"
OpenTelemetryAPI = "0.4"
Reexport = "1"
julia = "1"

[extras]
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "LoggingExtras"]
