name = "OpenTelemetryProto"
uuid = "cc651e92-2989-4f95-bcc3-32e6fb6ac025"
authors = ["Jun Tian <tianjun.cpp@gmail.com>"]
version = "0.13.1"

[deps]
ProtoBuf = "3349acd9-ac6a-5e09-bcdb-63829b23a429"
gRPCClient = "aaca4a50-36af-4a1d-b878-4c443f2061ad"

[compat]
ProtoBuf = "0.11"
gRPCClient = "0.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
