name = "OpenTelemetryAPI"
uuid = "4f63ef3d-5940-44e7-a611-2d97696cffc9"
authors = ["Jun Tian <tianjun.cpp@gmail.com>"]
version = "0.0.4"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
julia = "1.6"

[extras]
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "LoggingExtras"]
